# Generated by Django 4.0.7 on 2023-01-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0004_contenido_foro_evento_contenidos_alter_evento_semana'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='modulo',
        ),
        migrations.AddField(
            model_name='foro',
            name='modulo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='entrys.modulo'),
            preserve_default=False,
        ),
    ]
