# Generated by Django 4.0.7 on 2023-01-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=300)),
                ('nickname', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('profesor', models.BooleanField()),
            ],
        ),
    ]
