# Generated by Django 4.0.7 on 2023-01-16 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_calificacion_curso_grupo_tema_usuario_evento'),
        ('entrys', '0003_contenido_ejercicio_modulo_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='contenido',
            field=models.ManyToManyField(to='entrys.contenido'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.curso'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='evento',
            field=models.ManyToManyField(through='Usuarios.Calificacion', to='entrys.evento'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='usuarios',
            field=models.ManyToManyField(to='Usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrys.year'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrys.evento'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.grupo'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Usuarios.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='temaInv',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Usuarios.tema'),
            preserve_default=False,
        ),
    ]
