# Generated by Django 4.0.7 on 2023-01-23 21:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_tema_nombre_usuario_numtemp_alter_tema_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 1, 23, 21, 54, 14, 86526, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.grupo'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.FloatField(),
        ),
    ]
