# Generated by Django 4.0.7 on 2023-01-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('tipo', models.CharField(max_length=300)),
                ('semana', models.IntegerField(max_length=10)),
                ('contenido', models.CharField(choices=[('pdf', 'pdf'), ('video', 'video'), ('plainText', 'plainTExt')], default='video', max_length=20)),
                ('comentario', models.TextField()),
            ],
        ),
    ]
