# Generated by Django 4.0.7 on 2023-01-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='semana',
            field=models.IntegerField(),
        ),
    ]
