# Generated by Django 4.0.7 on 2023-01-16 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0002_alter_evento_semana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('ubic', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('puntaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloMod', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipo',
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloSem', models.CharField(max_length=300)),
                ('seman', models.IntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrys.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=1000)),
                ('correcta', models.BooleanField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrys.ejercicio')),
            ],
        ),
        migrations.AddField(
            model_name='modulo',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrys.year'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrys.evento'),
        ),
    ]
