# Generated by Django 4.0.7 on 2023-01-16 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('entrys', '0003_contenido_ejercicio_modulo_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='foro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.foro'),
        ),
        migrations.AddField(
            model_name='evento',
            name='contenidos',
            field=models.ManyToManyField(to='entrys.contenido'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrys.semana'),
        ),
    ]
