# Generated by Django 4.0.7 on 2023-01-21 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_comentario_modulo_foro_modulo'),
        ('entrys', '0005_evento_comentariosimple_evento_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='foro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.foro'),
        ),
    ]
