# Generated by Django 4.0.7 on 2023-01-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0006_alter_contenido_foro'),
    ]

    operations = [
        migrations.AddField(
            model_name='semana',
            name='nombre',
            field=models.CharField(default='AAAA', max_length=1000),
            preserve_default=False,
        ),
    ]
