# Generated by Django 4.0.7 on 2023-01-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0007_semana_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='semana',
            name='descripcion',
            field=models.TextField(default='A'),
            preserve_default=False,
        ),
    ]
