# Generated by Django 4.0.7 on 2023-01-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0008_semana_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semana',
            name='nombre',
        ),
        migrations.AddField(
            model_name='contenido',
            name='titulo',
            field=models.CharField(default='Soy un pdf o un video', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contenido',
            name='tipo',
            field=models.CharField(choices=[('pdf', 'pdf'), ('video', 'video')], max_length=100),
        ),
    ]
