# Generated by Django 4.0.7 on 2023-01-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0009_remove_semana_nombre_contenido_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='descripcion',
            field=models.CharField(default='Esta es la descripcion del ejercicio de la semana 31 jeje', max_length=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='titulo',
            field=models.CharField(default='Este es el titulo del ejercicio de la semana 31 juasjuas', max_length=200),
            preserve_default=False,
        ),
    ]
