# Generated by Django 4.0.7 on 2023-01-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0010_ejercicio_descripcion_ejercicio_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='formType',
            field=models.CharField(choices=[('checkbox', 'checkbox'), ('radio', 'radio'), ('text', 'text')], default='checkbox', max_length=100),
            preserve_default=False,
        ),
    ]
